# Generated by Django 5.0.1 on 2024-01-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.BooleanField(blank=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
