# Generated by Django 5.0.1 on 2024-01-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0002_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='brandimg'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
