# Generated by Django 5.0.1 on 2024-01-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0005_jobcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcategory',
            old_name='is_active',
            new_name='status',
        ),
    ]
