# Generated by Django 5.0.1 on 2024-01-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0007_eventgallery_eventgalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgalleryimage',
            name='image',
            field=models.ImageField(null=True, upload_to='galleryimg'),
        ),
    ]
