# Generated by Django 5.0.1 on 2024-01-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0012_managementteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('message', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='testimonialimg')),
                ('status', models.BooleanField(blank=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
