# Generated by Django 5.0.1 on 2024-01-16 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0013_companytestimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccancyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_category', to='deepapp.jobcategory')),
            ],
        ),
    ]
