# Generated by Django 5.0.1 on 2024-01-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0015_historydetails_historyimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyimage',
            old_name='histiry',
            new_name='history',
        ),
    ]
