# Generated by Django 5.0.1 on 2024-01-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0016_rename_histiry_historyimage_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.TextField(null=True)),
                ('message', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
