# Generated by Django 5.0.1 on 2024-01-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0018_supermarkets_alter_contactusdetails_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supermarkets',
        ),
    ]
