# Generated by Django 5.0.1 on 2024-01-17 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0024_alter_productdetails_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='deepapp.product'),
        ),
    ]
