# Generated by Django 5.0.1 on 2024-01-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0025_alter_productdetails_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccancydetails',
            name='type',
            field=models.TextField(null=True),
        ),
    ]
