# Generated by Django 5.0.1 on 2024-01-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0026_vaccancydetails_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccancydetails',
            name='salary',
            field=models.TextField(null=True),
        ),
    ]
