# Generated by Django 5.0.1 on 2024-01-23 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0027_vaccancydetails_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(null=True)),
                ('last_name', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('mobile_no', models.TextField(null=True)),
                ('notice', models.TextField(null=True)),
                ('linkedin', models.TextField(null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vaccancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deepapp.vaccancydetails')),
            ],
        ),
    ]
