# Generated by Django 5.0.1 on 2024-01-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0028_applicationdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdetails',
            name='vaccancy',
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='job',
            field=models.TextField(null=True),
        ),
    ]
