# Generated by Django 5.0.1 on 2024-01-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0029_remove_applicationdetails_vaccancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_product',
            field=models.SlugField(blank=True, default='', editable=False, max_length=250, null=True),
        ),
    ]
