# Generated by Django 5.0.1 on 2024-01-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0030_product_slug_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='canonical',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='keyword',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='metatag',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tag',
            field=models.TextField(null=True),
        ),
    ]
