# Generated by Django 5.0.1 on 2024-02-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0032_applicationdetails_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
