# Generated by Django 5.0.1 on 2024-02-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0033_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='sub_categories',
            field=models.TextField(null=True),
        ),
    ]
