# Generated by Django 5.0.1 on 2024-03-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0034_productdetails_sub_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdetails',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='portfolio',
            field=models.TextField(null=True),
        ),
    ]
