# Generated by Django 5.0.1 on 2024-03-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0035_applicationdetails_date_applicationdetails_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='how_to_cook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='shelf_life',
            field=models.TextField(blank=True, null=True),
        ),
    ]
