# Generated by Django 5.0.1 on 2024-03-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0037_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='aboutusimg')),
                ('title', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
