# Generated by Django 5.0.1 on 2024-03-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0038_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='sequence',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sequence',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventgallery',
            name='sequence',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sequence',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
