# Generated by Django 5.0.1 on 2024-03-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0039_brand_sequence_category_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
