# Generated by Django 5.0.1 on 2024-03-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0041_contactusdetails_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactusdetails',
            name='is_active',
        ),
    ]
