# Generated by Django 5.0.1 on 2024-03-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0042_remove_contactusdetails_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusdetails',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
