# Generated by Django 5.0.1 on 2024-03-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0046_historyimage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdetails',
            name='type',
            field=models.TextField(null=True),
        ),
    ]
