# Generated by Django 5.0.1 on 2024-03-27 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0047_newsdetails_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdetails',
            name='vaccancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deepapp.vaccancydetails'),
        ),
        migrations.AlterField(
            model_name='applicationdetails',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
