# Generated by Django 5.0.1 on 2024-03-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0048_applicationdetails_vaccancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdetails',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
