# Generated by Django 5.0.1 on 2024-03-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0049_applicationdetails_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementteam',
            name='sequence',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
