# Generated by Django 5.0.1 on 2024-03-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0050_managementteam_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdetails',
            name='sequence',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
