# Generated by Django 5.0.1 on 2024-04-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0051_newsdetails_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
