# Generated by Django 5.0.1 on 2024-08-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0052_alter_recipeingredients_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.TextField(blank=True, null=True)),
                ('title_tag', models.TextField(null=True)),
                ('metatag', models.TextField(null=True)),
                ('keyword', models.TextField(null=True)),
                ('canonical', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
