# Generated by Django 5.0.1 on 2024-08-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0053_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image_alt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
