# Generated by Django 5.0.1 on 2024-08-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0054_brand_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_alt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
