# Generated by Django 5.0.1 on 2024-08-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0057_certification_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytestimonial',
            name='image_alt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managementteam',
            name='image_alt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
