# Generated by Django 5.0.1 on 2024-08-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0058_companytestimonial_image_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdetails',
            name='image_alt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
