# Generated by Django 5.0.1 on 2024-08-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0059_newsdetails_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipedetails',
            name='image_alt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
