# Generated by Django 5.0.1 on 2024-08-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0061_historydetails_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetails',
            name='canonical',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogdetails',
            name='keyword',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogdetails',
            name='metatag',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogdetails',
            name='title_tag',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsdetails',
            name='canonical',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsdetails',
            name='keyword',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsdetails',
            name='metatag',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsdetails',
            name='title_tag',
            field=models.TextField(null=True),
        ),
    ]
