# Generated by Django 5.0.1 on 2024-08-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0062_blogdetails_canonical_blogdetails_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetails',
            name='image_alt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
