# Generated by Django 5.0.1 on 2024-08-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0063_blogdetails_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgallery',
            name='image_alt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
