# Generated by Django 5.0.1 on 2024-09-06 03:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0064_eventgallery_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetails',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
