# Generated by Django 5.0.1 on 2024-09-06 03:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepapp', '0065_blogdetails_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, max_length=255, null=True, populate_from='title', unique=True),
        ),
    ]
