# Generated by Django 5.1.3 on 2025-04-15 15:56

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatusTimestampBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BlogDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(null=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        populate_from="title",
                        unique=True,
                    ),
                ),
                ("name", models.TextField(null=True)),
                ("description", models.TextField(null=True)),
                ("location", models.TextField(null=True)),
                ("date", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoryDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.TextField(null=True)),
                ("title", models.TextField(null=True)),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewsDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(null=True)),
                ("sequence", models.PositiveIntegerField(null=True)),
                ("name", models.TextField(null=True)),
                ("type", models.TextField(null=True)),
                ("description", models.TextField(null=True)),
                ("location", models.TextField(null=True)),
                ("date", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "statustimestampbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="company.statustimestampbase",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="about_us")),
                ("title", models.TextField(null=True)),
            ],
            bases=("company.statustimestampbase",),
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "statustimestampbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="company.statustimestampbase",
                    ),
                ),
                ("name", models.TextField(null=True)),
                ("sequence", models.PositiveIntegerField(null=True)),
                ("logo", models.FileField(blank=True, null=True, upload_to="brand")),
            ],
            bases=("company.statustimestampbase",),
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "statustimestampbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="company.statustimestampbase",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="certification")),
            ],
            bases=("company.statustimestampbase",),
        ),
        migrations.CreateModel(
            name="CompanyTestimonial",
            fields=[
                (
                    "statustimestampbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="company.statustimestampbase",
                    ),
                ),
                ("name", models.TextField(null=True)),
                ("message", models.TextField(null=True)),
                ("image", models.ImageField(null=True, upload_to="testimonials")),
            ],
            bases=("company.statustimestampbase",),
        ),
        migrations.CreateModel(
            name="ManagementTeam",
            fields=[
                (
                    "statustimestampbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="company.statustimestampbase",
                    ),
                ),
                ("designation", models.TextField(null=True)),
                ("name", models.TextField(null=True)),
                ("sequence", models.PositiveIntegerField(null=True)),
                ("image", models.ImageField(null=True, upload_to="management_team")),
            ],
            bases=("company.statustimestampbase",),
        ),
        migrations.CreateModel(
            name="SEO",
            fields=[
                (
                    "statustimestampbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="company.statustimestampbase",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("/", "Home"),
                            ("/blog/", "Blog"),
                            ("/products/", "Products"),
                            ("/career/", "Career"),
                            ("/about/", "About"),
                            ("/news-room/", "NewsRoom"),
                        ],
                        max_length=150,
                        null=True,
                    ),
                ),
                ("meta_title", models.TextField(null=True)),
                ("meta_tag", models.TextField(null=True)),
                ("meta_keyword", models.TextField(null=True)),
                ("canonical", models.TextField(null=True)),
                ("image_alt", models.TextField(blank=True, null=True)),
            ],
            bases=("company.statustimestampbase",),
        ),
        migrations.CreateModel(
            name="Supermarkets",
            fields=[
                (
                    "statustimestampbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="company.statustimestampbase",
                    ),
                ),
                ("images", models.ImageField(null=True, upload_to="supermarkets")),
            ],
            bases=("company.statustimestampbase",),
        ),
    ]
