# Generated by Django 5.1.3 on 2025-04-19 09:58

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aboutus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="aboutusimg")),
                ("title", models.TextField(null=True)),
                ("status", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BlogDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(null=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        populate_from="title",
                        unique=True,
                    ),
                ),
                ("name", models.TextField(null=True)),
                ("description", models.TextField(null=True)),
                ("location", models.TextField(null=True)),
                ("date", models.DateField(null=True)),
                ("title_tag", models.TextField(null=True)),
                ("metatag", models.TextField(null=True)),
                ("keyword", models.TextField(null=True)),
                ("canonical", models.TextField(null=True)),
                ("image_alt", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(blank=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(null=True)),
                ("sequence", models.PositiveIntegerField(null=True)),
                ("logo", models.FileField(blank=True, null=True, upload_to="brandimg")),
                ("image_alt", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(blank=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="certificationimg")),
                ("image_alt", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CompanyTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(null=True)),
                ("message", models.TextField(null=True)),
                ("image", models.ImageField(null=True, upload_to="testimonialimg")),
                ("image_alt", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(blank=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactUsDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(null=True)),
                ("location", models.TextField(null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("mobile_no", models.TextField(null=True)),
                ("message", models.TextField(null=True)),
                ("is_active", models.BooleanField(blank=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EnquiryDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.TextField(null=True)),
                ("name", models.TextField(null=True)),
                ("location", models.TextField(null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("mobile_no", models.TextField(null=True)),
                ("message", models.TextField(null=True)),
                ("is_active", models.BooleanField(blank=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(null=True)),
                ("sequence", models.PositiveIntegerField(null=True)),
                ("name", models.TextField(null=True)),
                ("description", models.TextField(null=True)),
                ("location", models.TextField(null=True)),
                ("date", models.DateField(null=True)),
                ("image_alt", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(blank=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoryDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.TextField(null=True)),
                ("title", models.TextField(null=True)),
                ("description", models.TextField(null=True)),
                ("image_alt", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(blank=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ManagementTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.TextField(null=True)),
                ("name", models.TextField(null=True)),
                ("sequence", models.PositiveIntegerField(null=True)),
                ("image", models.ImageField(null=True, upload_to="teamimg")),
                ("image_alt", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(blank=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewsDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(null=True)),
                ("sequence", models.PositiveIntegerField(null=True)),
                ("name", models.TextField(null=True)),
                ("type", models.TextField(null=True)),
                ("description", models.TextField(null=True)),
                ("location", models.TextField(null=True)),
                ("date", models.DateField(null=True)),
                ("title_tag", models.TextField(null=True)),
                ("metatag", models.TextField(null=True)),
                ("keyword", models.TextField(null=True)),
                ("canonical", models.TextField(null=True)),
                ("image_alt", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(blank=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PromotionDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(null=True)),
                ("name", models.TextField(null=True)),
                ("description", models.TextField(null=True)),
                ("location", models.TextField(null=True)),
                ("date", models.DateField(null=True)),
                ("status", models.BooleanField(blank=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Seo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.TextField(blank=True, null=True)),
                ("title_tag", models.TextField(null=True)),
                ("metatag", models.TextField(null=True)),
                ("keyword", models.TextField(null=True)),
                ("canonical", models.TextField(null=True)),
                ("status", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supermarkets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="supermarketsimg")),
                ("image_alt", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(blank=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="blogimg")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_image",
                        to="company.blogdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="galleryimg")),
                ("is_active", models.BooleanField(blank=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_image",
                        to="company.eventgallery",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="historyimg")),
                ("is_active", models.BooleanField(blank=True, default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_image",
                        to="company.historydetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="newsimg")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_image",
                        to="company.newsdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromotionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="promotionimg")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_image",
                        to="company.promotiondetails",
                    ),
                ),
            ],
        ),
    ]
