# Generated by Django 5.1.3 on 2025-04-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="title",
            field=models.CharField(max_length=350),
        ),
    ]
