# Generated by Django 5.1.3 on 2025-04-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogdetails",
            options={"verbose_name_plural": "Blog Details"},
        ),
        migrations.AlterModelOptions(
            name="newsdetails",
            options={"verbose_name_plural": "News Details"},
        ),
        migrations.AlterModelOptions(
            name="promotiondetails",
            options={"verbose_name_plural": "Promotion Details"},
        ),
    ]
