# Generated by Django 5.2 on 2025-05-16 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productdetails",
            ),
        ),
        migrations.AddField(
            model_name="eventimage",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_image",
                to="company.event",
            ),
        ),
        migrations.AddField(
            model_name="historyimage",
            name="history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_image",
                to="company.history",
            ),
        ),
        migrations.AddField(
            model_name="newsimage",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_image",
                to="company.news",
            ),
        ),
        migrations.AddField(
            model_name="promotionimage",
            name="promotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotion_image",
                to="company.promotion",
            ),
        ),
    ]
