# Generated by Django 5.2 on 2025-05-12 08:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, max_length=100, null=True, populate_from='content', unique=True),
        ),
    ]
