# Generated by Django 5.2 on 2025-04-30 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog Detail', 'verbose_name_plural': 'Blog Details'},
        ),
        migrations.AlterModelOptions(
            name='blogimage',
            options={'verbose_name': 'Blog Image', 'verbose_name_plural': 'Blog Images'},
        ),
        migrations.AlterModelOptions(
            name='companytestimonial',
            options={'verbose_name': 'Company Testimonial', 'verbose_name_plural': 'Company Testimonials'},
        ),
        migrations.AlterModelOptions(
            name='eventimage',
            options={'verbose_name': 'Event Image', 'verbose_name_plural': 'Event Images'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
        migrations.AlterModelOptions(
            name='historyimage',
            options={'verbose_name': 'History Image', 'verbose_name_plural': 'History Images'},
        ),
        migrations.AlterModelOptions(
            name='managementteam',
            options={'verbose_name': 'Management Team', 'verbose_name_plural': 'Management Teams'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name': 'News Image', 'verbose_name_plural': 'News Images'},
        ),
        migrations.AlterModelOptions(
            name='promotionimage',
            options={'verbose_name': 'Promotion Image', 'verbose_name_plural': 'Promotion Images'},
        ),
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'SEO', 'verbose_name_plural': 'SEOs'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
