# Generated by Django 5.2 on 2025-04-21 16:08

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_blogdetails_options_alter_newsdetails_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image_alt',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='blogimage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to=company.models.image_upload_path),
        ),
        migrations.AddField(
            model_name='eventgalleryimage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='historyimage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='newsgalleryimage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='promotionimage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
