# Generated by Django 5.2 on 2025-05-13 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_news_slug"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enquiry",
            old_name="mobile_number",
            new_name="phone_number",
        ),
        migrations.AddField(
            model_name="enquiry",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productdetails",
            ),
        ),
    ]
