# Generated by Django 5.2 on 2025-05-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_rename_mobile_number_enquiry_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="name",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="history",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="name",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
