# Generated by Django 5.2 on 2025-05-16 08:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "company",
            "0004_alter_blog_date_alter_blog_location_alter_blog_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=True,
                max_length=100,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
