# Generated by Django 5.1.3 on 2025-04-26 08:04

import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VaccancyDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                (
                    "type",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("full time", "Full-Time"),
                            ("part time", "Part-Time"),
                            ("remote", "Remote"),
                            ("contract", "Contract"),
                        ],
                        max_length=35,
                        null=True,
                    ),
                ),
                ("salary", models.PositiveIntegerField(null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_category",
                        to="career.jobcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApplicationDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("job", models.CharField(max_length=150)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.TextField(null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, null=True, region=None
                    ),
                ),
                (
                    "notice_period",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate Join"),
                            ("2_weeks", "2 Weeks"),
                            ("1_month", "1 Month"),
                        ],
                        max_length=100,
                    ),
                ),
                ("linkedin_url", models.URLField(null=True)),
                ("portfolio_url", models.URLField(null=True)),
                ("date_of_birth", models.DateField(null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("upload_cv", models.FileField(upload_to="cv")),
                ("cover_letter", models.FileField(upload_to="cover_letter")),
                (
                    "vaccancy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="career.vaccancydetails",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
