# Generated by Django 5.1.3 on 2025-04-26 03:42

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationdetails",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="vaccancydetails",
            name="salary",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
