# Generated by Django 5.2 on 2025-05-05 09:22

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdetails',
            name='vaccancy',
        ),
        migrations.AlterModelOptions(
            name='applicationdetails',
            options={'verbose_name_plural': 'Application Details'},
        ),
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name_plural': 'Job categories'},
        ),
        migrations.RemoveField(
            model_name='applicationdetails',
            name='job',
        ),
        migrations.AlterField(
            model_name='applicationdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='VacancyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('hiring_status', models.CharField(blank=True, help_text="Status of the job's hiring process (e.g., 'Urgent Requirement').", max_length=100, null=True)),
                ('type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('full time', 'Full-Time'), ('part time', 'Part-Time'), ('remote', 'Remote'), ('contract', 'Contract')], max_length=35, null=True)),
                ('salary', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_category', to='career.jobcategory')),
            ],
            options={
                'verbose_name_plural': 'Vacancy Details',
            },
        ),
        migrations.AddField(
            model_name='applicationdetails',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.vacancydetails'),
        ),
        migrations.DeleteModel(
            name='VaccancyDetails',
        ),
    ]
