# Generated by Django 5.2 on 2025-05-12 08:30

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancydetails",
            name="type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("full time", "Full-Time"),
                    ("part time", "Part-Time"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                ],
                max_length=33,
                null=True,
            ),
        ),
    ]
