# Generated by Django 5.1.3 on 2025-04-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccancydetails",
            name="salary",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
