# Generated by Django 5.2 on 2025-04-30 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VaccancyDetails',
            new_name='VacancyDetails',
        ),
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name_plural': 'Job categories'},
        ),
        migrations.RenameField(
            model_name='applicationdetails',
            old_name='vaccancy',
            new_name='vacancy',
        ),
    ]
