# Generated by Django 5.2 on 2025-05-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0002_remove_applicationdetails_vaccancy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationdetails",
            name="cover_letter",
            field=models.FileField(blank=True, null=True, upload_to="cover_letter"),
        ),
        migrations.AlterField(
            model_name="applicationdetails",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applicationdetails",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicationdetails",
            name="notice_period",
            field=models.CharField(
                choices=[
                    ("", "Select any"),
                    ("immediate", "Immediate Join"),
                    ("2_weeks", "2 Weeks"),
                    ("1_month", "1 Month"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="applicationdetails",
            name="portfolio_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
