# Generated by Django 5.1.3 on 2025-04-21 15:18

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0002_alter_vaccancydetails_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationdetails",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
    ]
