# Generated by Django 5.2 on 2025-04-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_rename_vaccancydetails_vacancydetails_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationdetails',
            options={'verbose_name_plural': 'Application Details'},
        ),
        migrations.AlterModelOptions(
            name='vacancydetails',
            options={'verbose_name_plural': 'Vacancy Details'},
        ),
        migrations.AlterField(
            model_name='applicationdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
