# Generated by Django 5.2 on 2025-05-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_alter_applicationdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancydetails',
            name='hiring_status',
            field=models.CharField(blank=True, help_text="Status of the job's hiring process (e.g., 'Urgent Requirement').", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancydetails',
            name='salary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
