# Generated by Django 5.2 on 2025-05-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0003_alter_applicationdetails_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationdetails",
            name="job",
        ),
    ]
