# Generated by Django 5.2 on 2025-04-30 17:06

import autoslug.fields
import company.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to=company.models.image_upload_path)),
                ('image_alt', models.CharField(blank=True, max_length=125, null=True)),
                ('status', models.BooleanField(default=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='company.brand')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to=company.models.image_upload_path)),
                ('image_alt', models.CharField(blank=True, max_length=125, null=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('homepage', models.BooleanField(default=False)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('local catch', 'Local Catch'), ('imported', 'Imported'), ('value added', 'Value Added')], max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, max_length=100, null=True, populate_from='name', unique=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='company.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_categories', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('net_weight', models.CharField(blank=True, max_length=100)),
                ('nutrition', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('storage_instructions', models.TextField(blank=True)),
                ('shelf_life', models.CharField(blank=True, max_length=150)),
                ('how_to_cook', models.TextField(blank=True)),
                ('allergic', models.TextField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=2000)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('packing', models.CharField(blank=True, max_length=2000)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, max_length=100, null=True, populate_from='name', unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='products.category')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Detail',
                'verbose_name_plural': 'Product Details',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
    ]
