# Generated by Django 5.1.3 on 2025-04-21 15:10

import autoslug.fields
import company.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "company",
            "0002_alter_blogdetails_options_alter_newsdetails_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to=company.models.image_upload_path
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=200)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand",
                        to="company.brand",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("type", models.CharField(blank=True, max_length=150)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        blank=True,
                        editable=True,
                        max_length=100,
                        null=True,
                        populate_from="title",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("image_alt", models.CharField(blank=True, max_length=100)),
                ("homepage", models.BooleanField(default=False)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_brand",
                        to="company.brand",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_categories", models.CharField(max_length=100, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                (
                    "product_code",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("net_weight", models.CharField(blank=True, max_length=100)),
                ("nutrition", models.TextField(blank=True)),
                ("ingredients", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                ("storage_instructions", models.TextField(blank=True)),
                ("shelf_life", models.CharField(blank=True, max_length=150)),
                ("how_to_cook", models.TextField(blank=True)),
                ("allergic", models.TextField(blank=True)),
                ("grade", models.CharField(blank=True, max_length=2000)),
                ("origin", models.CharField(blank=True, max_length=100)),
                ("packing", models.CharField(blank=True, max_length=2000)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_details",
                        to="products.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_details",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to=company.models.image_upload_path
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, max_length=350, null=True),
                ),
                ("image_alt", models.CharField(blank=True, max_length=100)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.brand",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecipeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to=company.models.image_upload_path
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_image",
                        to="products.recipedetails",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=150)),
                ("amount", models.IntegerField(default=0)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="products.recipedetails",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
