# Generated by Django 5.2 on 2025-04-29 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipedetails',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='recipeimage',
            name='recipe',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productdetails',
            options={'verbose_name': 'Product Detail', 'verbose_name_plural': 'Product Details'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.DeleteModel(
            name='RecipeIngredients',
        ),
        migrations.DeleteModel(
            name='RecipeDetails',
        ),
        migrations.DeleteModel(
            name='RecipeImage',
        ),
    ]
