# Generated by Django 5.2 on 2025-04-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_alt',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='image_alt',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
