# Generated by Django 5.1.3 on 2025-04-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="product"),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
