<<<<<<< HEAD
# Generated by Django 5.1.3 on 2025-04-26 03:42

import autoslug.fields
=======
# Generated by Django 5.1.3 on 2025-04-24 11:17

import autoslug.fields
import django.db.models.deletion
>>>>>>> 5753479191c4ac526c76a10ddddfda4b713c216a
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("products", "0001_initial"),
=======
        ('products', '0001_initial'),
>>>>>>> 5753479191c4ac526c76a10ddddfda4b713c216a
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="productdetails",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=True,
                max_length=100,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=True,
                max_length=100,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[
                    ("local catch", "Local Catch"),
                    ("imported", "Imported"),
                    ("value added", "Value Added"),
                ],
                max_length=200,
            ),
=======
            model_name='productdetails',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, max_length=100, null=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, max_length=100, null=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('local catch', 'Local Catch'), ('imported', 'Imported'), ('value added', 'Value Added')], max_length=200),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
>>>>>>> 5753479191c4ac526c76a10ddddfda4b713c216a
        ),
    ]
