# Generated by Django 5.1.3 on 2025-04-26 04:21

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productdetails_slug_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=company.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_alt',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
