# Generated by Django 5.2 on 2025-05-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_productdetails_sub_categories_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[
                    ("", "Select the Type"),
                    ("local catch", "Local Catch"),
                    ("imported", "Imported"),
                    ("value added", "Value Added"),
                ],
                max_length=200,
            ),
        ),
    ]
